# Generated by Django 5.2.6 on 2025-10-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('read', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
